### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect:

### ISSUE THREAD

**Issue by Emilevandelouw** [rasmuse/eust#4]
* Eurostat tools version: eust 0.4.0
* Python version: 
* Operating System: Windows 10 pro (64 bit)

### Description

when trying to get data i keep on getting error: OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 

### What I Did

>>> import eust
>>> eust.download_table('acf_d_rea')  # that's it
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Emile.WST202\AppData\Local\Programs\Python\Python38-32\lib\site-packages\eust\tables\__init__.py", line 69, in download_table
    if version_dir.exists():
  File "C:\Users\Emile.WST202\AppData\Local\Programs\Python\Python38-32\lib\pathlib.py", line 1385, in exists
    self.stat()
  File "C:\Users\Emile.WST202\AppData\Local\Programs\Python\Python38-32\lib\pathlib.py", line 1191, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '..\\eurostat-data\\tables\\acf_d_rea\\2015-10-28 23:00:02'
>>>

**Comment by rasmuse** [comment]
Thank you for submitting this. I have not yet tested the library on Windows, so I'm not surprised you are having a problem.

Not entirely sure what is going wrong though. I will try to reproduce on a Windows machine and then get back to you.

**Comment by rasmuse** [comment]
The issue was that the directory name `eurostat-data\tables\acf_d_rea\2015-10-28 23:00:02` contains colons, which are not allowed in paths on Windows.

Please install the latest version (v0.5.1) and you should be able to replicate this:

```
>>> import eust
>>> eust.download_table('acf_d_rea')
>>> eust.read_table_data('acf_d_rea')
                                      value  flag
unit enterpr nace_r2 reason geo time             
PC   HG      B-E     BTIN   BE  2007    4.3  None
                                2010    9.1  None
                            BG  2007   16.9  None
                                2010    8.1  None
                            CY  2007    0.0  None
...                                     ...   ...
     YHG     M       OTH    SE  2010    0.0  None
                            SK  2007    0.0  None
                                2010    0.0  None
                            UK  2007    0.0  None
                                2010    0.0  None

[6720 rows x 2 columns]
```
